import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HeroUIProvider } from '@heroui/react'
import Navbar from './Navbar'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ZeroBug',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <HeroUIProvider>{children}</HeroUIProvider>
        </Providers>
      </body>
    </html>
  )
}
